### ISSUE TITLE
Chart offset fixing

### ISSUE THREAD

**Issue by A-random-githuber** [feightwywx/aff.arcaea.icu#2]
![ebyPGDqwWP](https://user-images.githubusercontent.com/89432931/130543905-a86311d9-b8f7-4a7a-9464-14c3423dd4d6.png)
Hi, ever since my friend introduce the aff.arcaea.icu to me. It helps me alot, especially the chart offset fixing tool. When i using the tool to fix the chart, it always generates a spare base timing. Do you have any idea why?

**Comment by A-random-githuber** [comment]
![brave_dSUVaQo35F](https://user-images.githubusercontent.com/89432931/130544087-7af38d3b-7971-4bf0-a8b1-ae56ee7ba235.png)
missed a pic bruh

**Comment by notmee1** [comment]
> ![brave_dSUVaQo35F](https://user-images.githubusercontent.com/89432931/130544087-7af38d3b-7971-4bf0-a8b1-ae56ee7ba235.png)
> missed a pic bruh

The picture show that the input have 3 base spare timing, have you ever tried to delete it?

**Comment by innocentvoice** [comment]
Probably you should check the input

**Comment by feightwywx** [comment]
I did this on purpose.
The reason is, every .aff file (and timinggroup) should have one base timing, which would be offseted during offset fixing. Chart offset fixing tool will generate base timings for chart and each timinggroup when fixing, otherwise the fixed chart (and timinggroups) may lack a base timing.
If you don't want this happen, input a chart snippet (with **NO** AudioOffset, TPDF, or even `timinggroup()`s, etc.) instead of a full chart, like this:
```
timing(0,245.00,4.00);
arc(1469,1959,0.50,1.00,si,1.00,1.00,1,none,false);
(2938,4);
```

**Comment by A-random-githuber** [comment]
> I did this on purpose.
> The reason is, every .aff file (and timinggroup) should have one base timing, which would be offseted during offset fixing. Chart offset fixing tool will generate base timings for chart and each timinggroup when fixing, otherwise the fixed chart (and timinggroups) may lack a base timing.
> If you don't want this happen, input a chart snippet (with **NO** AudioOffset, TPDF, or even `timinggroup()`s, etc.) instead of a full chart, like this:
> 
> ```
> timing(0,245.00,4.00);
> arc(1469,1959,0.50,1.00,si,1.00,1.00,1,none,false);
> (2938,4);
> ```

Ohhhh i get it now. Thanks a lot!
